// Generated by gencpp from file voxblox_msgs/FilePath.msg
// DO NOT EDIT!


#ifndef VOXBLOX_MSGS_MESSAGE_FILEPATH_H
#define VOXBLOX_MSGS_MESSAGE_FILEPATH_H

#include <ros/service_traits.h>


#include <voxblox_msgs/FilePathRequest.h>
#include <voxblox_msgs/FilePathResponse.h>


namespace voxblox_msgs
{

struct FilePath
{

typedef FilePathRequest Request;
typedef FilePathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FilePath
} // namespace voxblox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::voxblox_msgs::FilePath > {
  static const char* value()
  {
    return "a1f82596372c52a517e1fe32d1e998e8";
  }

  static const char* value(const ::voxblox_msgs::FilePath&) { return value(); }
};

template<>
struct DataType< ::voxblox_msgs::FilePath > {
  static const char* value()
  {
    return "voxblox_msgs/FilePath";
  }

  static const char* value(const ::voxblox_msgs::FilePath&) { return value(); }
};


// service_traits::MD5Sum< ::voxblox_msgs::FilePathRequest> should match 
// service_traits::MD5Sum< ::voxblox_msgs::FilePath > 
template<>
struct MD5Sum< ::voxblox_msgs::FilePathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::voxblox_msgs::FilePath >::value();
  }
  static const char* value(const ::voxblox_msgs::FilePathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::voxblox_msgs::FilePathRequest> should match 
// service_traits::DataType< ::voxblox_msgs::FilePath > 
template<>
struct DataType< ::voxblox_msgs::FilePathRequest>
{
  static const char* value()
  {
    return DataType< ::voxblox_msgs::FilePath >::value();
  }
  static const char* value(const ::voxblox_msgs::FilePathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::voxblox_msgs::FilePathResponse> should match 
// service_traits::MD5Sum< ::voxblox_msgs::FilePath > 
template<>
struct MD5Sum< ::voxblox_msgs::FilePathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::voxblox_msgs::FilePath >::value();
  }
  static const char* value(const ::voxblox_msgs::FilePathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::voxblox_msgs::FilePathResponse> should match 
// service_traits::DataType< ::voxblox_msgs::FilePath > 
template<>
struct DataType< ::voxblox_msgs::FilePathResponse>
{
  static const char* value()
  {
    return DataType< ::voxblox_msgs::FilePath >::value();
  }
  static const char* value(const ::voxblox_msgs::FilePathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VOXBLOX_MSGS_MESSAGE_FILEPATH_H
